run:
	fvm flutter run
open:
	open -a Simulator
format:
	fvm flutter format lib
	fvm flutter format test
install:
	fvm flutter pub get
migrate:
	fvm flutter pub run build_runner watch --delete-conflicting-outputs
setup:
	mv .env.sample .env
